services:
  mifosx-web-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_ENVIRONMENT_OPTIONS=--configuration production
        - BUILDER_IMAGE=node:20-alpine
        - NGINX_IMAGE=nginx:1.19.3
        - NPM_REGISTRY_URL=https://registry.npmjs.org/
        - PUPPETEER_DOWNLOAD_HOST_ARG=https://storage.googleapis.com
        - PUPPETEER_CHROMIUM_REVISION_ARG=1011831
    ports:
      - '4200:80'
    environment:
      - FINERACT_API_URL=https://fineract.finxi.mx
      - FINERACT_API_PROVIDER=/fineract-provider/api
      - FINERACT_API_VERSION=/v1
      - FINERACT_PLATFORM_TENANT_IDENTIFIER=default
      - MIFOS_DEFAULT_LANGUAGE=es-MX
      - MIFOS_SUPPORTED_LANGUAGES=es-MX,en-US
      - MIFOS_PRELOAD_CLIENTS=true
      - MIFOS_DEFAULT_CHAR_DELIMITER=,
